package dataengineer

import (
	"context"
	"fmt"
	"strings"

	"github.com/younjinjeong/microfoundry/pkg/agents"
	"github.com/younjinjeong/microfoundry/pkg/claude"
	"github.com/younjinjeong/microfoundry/pkg/github"
)

// Agent is the Data Engineer Agent that recommends data structures.
type Agent struct {
	claude *claude.Client
	gh     *github.Client
}

// New creates a new Data Engineer Agent.
func New(claudeClient *claude.Client, ghClient *github.Client) *Agent {
	return &Agent{
		claude: claudeClient,
		gh:     ghClient,
	}
}

func (a *Agent) Role() agents.AgentRole {
	return agents.RoleDataEngineer
}

func (a *Agent) Run(ctx context.Context, pctx *agents.PipelineContext) (*agents.AgentResult, error) {
	// 1. Read the Epic issue
	issue, err := a.gh.ReadIssue(pctx.IssueNumber)
	if err != nil {
		return nil, fmt.Errorf("reading issue #%d: %w", pctx.IssueNumber, err)
	}

	// 2. Collect existing comments
	var commentBodies []string
	for _, c := range issue.Comments {
		commentBodies = append(commentBodies, c.Body)
	}

	// 3. Ask Claude for data structure recommendations
	prompt := buildDataEngineerPrompt(issue.Body, commentBodies)
	response, err := a.claude.Ask(ctx, systemPrompt, prompt)
	if err != nil {
		return nil, fmt.Errorf("Claude data analysis failed: %w", err)
	}

	// 4. Format and post as issue comment
	comment := formatDataComment(response)
	if err := a.gh.AddIssueComment(pctx.IssueNumber, comment); err != nil {
		return nil, fmt.Errorf("posting data engineer comment: %w", err)
	}

	return &agents.AgentResult{
		Success:     true,
		Summary:     fmt.Sprintf("Posted data structure recommendations on issue #%d", pctx.IssueNumber),
		Artifacts:   []agents.Artifact{{Type: "comment", Content: comment}},
		NextContext: pctx,
	}, nil
}

func formatDataComment(response string) string {
	var sb strings.Builder
	sb.WriteString("## Data Engineering Review\n\n")
	sb.WriteString(response)
	sb.WriteString("\n\n---\n*Generated by MicroFoundry Data Engineer Agent*\n")
	return sb.String()
}
