package analyzer

import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/younjinjeong/microfoundry/pkg/agents"
	"github.com/younjinjeong/microfoundry/pkg/claude"
	"github.com/younjinjeong/microfoundry/pkg/codebase"
	"github.com/younjinjeong/microfoundry/pkg/github"
)

// Agent is the Analyzer Agent that creates detailed Epic plans.
type Agent struct {
	claude  *claude.Client
	gh      *github.Client
	scanner *codebase.Scanner
}

// New creates a new Analyzer Agent.
func New(claudeClient *claude.Client, ghClient *github.Client, scanner *codebase.Scanner) *Agent {
	return &Agent{
		claude:  claudeClient,
		gh:      ghClient,
		scanner: scanner,
	}
}

func (a *Agent) Role() agents.AgentRole {
	return agents.RoleAnalyzer
}

func (a *Agent) Run(ctx context.Context, pctx *agents.PipelineContext) (*agents.AgentResult, error) {
	// 1. Scan reference CF codebases to build context
	codebaseCtx, err := a.scanner.BuildContext(pctx.RefCodebasePaths)
	if err != nil {
		return nil, fmt.Errorf("scanning codebase: %w", err)
	}

	// 2. Use Claude with extended thinking to create detailed plan
	prompt := buildAnalyzerPrompt(pctx.EpicTitle, pctx.EpicDescription, codebaseCtx)
	thinking, plan, err := a.claude.AskWithThinking(ctx, systemPrompt, prompt, 0)
	if err != nil {
		return nil, fmt.Errorf("Claude analysis failed: %w", err)
	}

	// 3. Format the issue body
	issueBody := formatIssuePlan(pctx.EpicTitle, pctx.EpicDescription, plan, thinking)

	// 4. Ensure labels exist
	_ = a.gh.CreateLabel("epic", "6F42C1", "Epic-level feature")
	_ = a.gh.CreateLabel("agent-generated", "0E8A16", "Generated by MicroFoundry agents")

	// 5. Create GitHub Issue with the plan
	issueNum, issueURL, err := a.gh.CreateIssue(
		fmt.Sprintf("[Epic] %s", pctx.EpicTitle),
		issueBody,
		[]string{"epic", "agent-generated"},
	)
	if err != nil {
		return nil, fmt.Errorf("creating GitHub issue: %w", err)
	}

	// 6. Create branch for the epic
	branchName := fmt.Sprintf("epic/%s", slugify(pctx.EpicTitle))
	if pctx.WorkDir != "" {
		if err := a.gh.CreateBranch(pctx.WorkDir, branchName); err != nil {
			return nil, fmt.Errorf("creating branch %s: %w", branchName, err)
		}
	}

	// 7. Update context
	result := *pctx
	result.IssueNumber = issueNum
	result.BranchName = branchName
	if result.Metadata == nil {
		result.Metadata = make(map[string]string)
	}
	result.Metadata["issue_url"] = issueURL

	return &agents.AgentResult{
		Success: true,
		Summary: fmt.Sprintf("Created issue #%d and branch %s", issueNum, branchName),
		Artifacts: []agents.Artifact{
			{Type: "issue", Content: issueBody, URL: issueURL},
			{Type: "branch", Content: branchName},
		},
		NextContext: &result,
	}, nil
}

func formatIssuePlan(title, description, plan, thinking string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Epic: %s\n\n", title))
	sb.WriteString(fmt.Sprintf("## Original Description\n%s\n\n", description))
	sb.WriteString("---\n\n")
	sb.WriteString("## Implementation Plan\n\n")
	sb.WriteString(plan)
	sb.WriteString("\n\n---\n\n")
	sb.WriteString("<details>\n<summary>Analysis Thinking Process</summary>\n\n")
	sb.WriteString(thinking)
	sb.WriteString("\n</details>\n\n")
	sb.WriteString("---\n*Generated by MicroFoundry Analyzer Agent*\n")
	return sb.String()
}

func slugify(s string) string {
	s = strings.ToLower(s)
	reg := regexp.MustCompile(`[^a-z0-9]+`)
	s = reg.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	if len(s) > 60 {
		s = s[:60]
	}
	return s
}
