package reviewer

import (
	"context"
	"fmt"
	"os/exec"
	"strings"

	"github.com/younjinjeong/microfoundry/pkg/agents"
	"github.com/younjinjeong/microfoundry/pkg/claude"
	"github.com/younjinjeong/microfoundry/pkg/github"
)

// Agent is the Review Agent that checks PRs for quality, security, and compliance.
type Agent struct {
	claude *claude.Client
	gh     *github.Client
}

// New creates a new Review Agent.
func New(claudeClient *claude.Client, ghClient *github.Client) *Agent {
	return &Agent{
		claude: claudeClient,
		gh:     ghClient,
	}
}

func (a *Agent) Role() agents.AgentRole {
	return agents.RoleReviewer
}

func (a *Agent) Run(ctx context.Context, pctx *agents.PipelineContext) (*agents.AgentResult, error) {
	// 1. Get PR diff
	diff, err := a.gh.GetPRDiff(pctx.PRNumber)
	if err != nil {
		return nil, fmt.Errorf("getting PR diff: %w", err)
	}

	// Truncate diff if too large for Claude context
	if len(diff) > 100000 {
		diff = diff[:100000] + "\n... [truncated]"
	}

	// 2. Gather dependency information
	depInfo := a.gatherDependencyInfo(pctx.WorkDir)

	// 3. Run individual checks in parallel via goroutines
	type checkResult struct {
		name   string
		result string
		err    error
	}
	results := make(chan checkResult, 5)

	// License check
	go func() {
		r, err := a.checkLicenses(ctx, pctx.WorkDir)
		results <- checkResult{"license", r, err}
	}()

	// Security check via govulncheck
	go func() {
		r, err := a.checkSecurity(ctx, pctx.WorkDir)
		results <- checkResult{"security", r, err}
	}()

	// Collect local check results
	var localChecks strings.Builder
	for i := 0; i < 2; i++ {
		cr := <-results
		if cr.err != nil {
			localChecks.WriteString(fmt.Sprintf("### %s Check\nError: %s\n\n", cr.name, cr.err))
		} else {
			localChecks.WriteString(fmt.Sprintf("### %s Check (local)\n%s\n\n", cr.name, cr.result))
		}
	}

	// 4. Ask Claude for comprehensive review (includes all 5 review areas)
	prompt := buildReviewPrompt(diff, depInfo+"\n\n"+localChecks.String())
	review, err := a.claude.Ask(ctx, systemPrompt, prompt)
	if err != nil {
		return nil, fmt.Errorf("Claude review failed: %w", err)
	}

	// 5. Determine review event based on content
	reviewEvent := "COMMENT"
	lowerReview := strings.ToLower(review)
	if strings.Contains(lowerReview, "fail") {
		reviewEvent = "REQUEST_CHANGES"
	}

	// 6. Post review on PR
	comment := formatReviewComment(review)
	if err := a.gh.AddPRReview(pctx.PRNumber, reviewEvent, comment); err != nil {
		// Fallback to regular comment if review fails
		if err2 := a.gh.AddPRComment(pctx.PRNumber, comment); err2 != nil {
			return nil, fmt.Errorf("posting review: %w", err)
		}
	}

	return &agents.AgentResult{
		Success:     true,
		Summary:     fmt.Sprintf("Review posted on PR #%d (%s). Awaiting human approval.", pctx.PRNumber, reviewEvent),
		Artifacts:   []agents.Artifact{{Type: "comment", Content: comment}},
		NextContext: pctx,
	}, nil
}

func (a *Agent) gatherDependencyInfo(workDir string) string {
	if workDir == "" {
		return "No working directory specified"
	}
	cmd := exec.Command("go", "list", "-m", "-json", "all")
	cmd.Dir = workDir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Sprintf("Could not list dependencies: %s", err)
	}
	// Truncate if too large
	result := string(out)
	if len(result) > 20000 {
		result = result[:20000] + "\n... [truncated]"
	}
	return result
}

func (a *Agent) checkLicenses(ctx context.Context, workDir string) (string, error) {
	if workDir == "" {
		return "Skipped — no working directory", nil
	}
	// Use go-licenses if available, otherwise just report dependencies
	cmd := exec.CommandContext(ctx, "go", "list", "-m", "all")
	cmd.Dir = workDir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("listing modules: %w", err)
	}
	return fmt.Sprintf("Dependencies listed for license review:\n```\n%s\n```", string(out)), nil
}

func (a *Agent) checkSecurity(ctx context.Context, workDir string) (string, error) {
	if workDir == "" {
		return "Skipped — no working directory", nil
	}
	// Try govulncheck
	cmd := exec.CommandContext(ctx, "govulncheck", "./...")
	cmd.Dir = workDir
	out, err := cmd.CombinedOutput()
	if err != nil {
		// govulncheck might not be installed
		return fmt.Sprintf("govulncheck not available or found issues:\n```\n%s\n```", string(out)), nil
	}
	return fmt.Sprintf("govulncheck passed:\n```\n%s\n```", string(out)), nil
}

func formatReviewComment(review string) string {
	var sb strings.Builder
	sb.WriteString("## MicroFoundry Review Agent Report\n\n")
	sb.WriteString(review)
	sb.WriteString("\n\n---\n")
	sb.WriteString("*Generated by MicroFoundry Review Agent*\n")
	sb.WriteString("*Awaiting human review and merge approval.*\n")
	return sb.String()
}
