package designer

import (
	"context"
	"fmt"
	"strings"

	"github.com/younjinjeong/microfoundry/pkg/agents"
	"github.com/younjinjeong/microfoundry/pkg/claude"
	"github.com/younjinjeong/microfoundry/pkg/github"
)

// Agent is the Product Designer Agent that assesses UI needs and generates mockups.
type Agent struct {
	claude     *claude.Client
	gh         *github.Client
	skipIfNoUI bool
}

// New creates a new Designer Agent.
func New(claudeClient *claude.Client, ghClient *github.Client, skipIfNoUI bool) *Agent {
	return &Agent{
		claude:     claudeClient,
		gh:         ghClient,
		skipIfNoUI: skipIfNoUI,
	}
}

func (a *Agent) Role() agents.AgentRole {
	return agents.RoleDesigner
}

func (a *Agent) Run(ctx context.Context, pctx *agents.PipelineContext) (*agents.AgentResult, error) {
	// 1. Read issue and all comments
	issue, err := a.gh.ReadIssue(pctx.IssueNumber)
	if err != nil {
		return nil, fmt.Errorf("reading issue #%d: %w", pctx.IssueNumber, err)
	}

	var commentBodies []string
	for _, c := range issue.Comments {
		commentBodies = append(commentBodies, c.Body)
	}

	// 2. Assess if UI is needed
	prompt := buildDesignerPrompt(issue.Body, commentBodies)
	assessment, err := a.claude.Ask(ctx, systemPrompt, prompt)
	if err != nil {
		return nil, fmt.Errorf("Claude UI assessment failed: %w", err)
	}

	needsUI := strings.HasPrefix(strings.ToLower(strings.TrimSpace(assessment)), "yes")

	if !needsUI {
		comment := "## Product Design Assessment\n\n" +
			"No web interface required for this Epic. The feature will be CLI-only.\n\n" +
			"**Assessment:** " + strings.TrimSpace(assessment) + "\n\n" +
			"---\n*Generated by MicroFoundry Designer Agent*\n"
		if err := a.gh.AddIssueComment(pctx.IssueNumber, comment); err != nil {
			return nil, fmt.Errorf("posting design assessment: %w", err)
		}
		return &agents.AgentResult{
			Success:     true,
			Summary:     "No UI needed for this Epic",
			NextContext: pctx,
		}, nil
	}

	// 3. Generate HTML mockup
	mockupPrompt := buildMockupPrompt(issue.Body, commentBodies)
	htmlDesign, err := a.claude.Ask(ctx, systemPrompt, mockupPrompt)
	if err != nil {
		return nil, fmt.Errorf("Claude mockup generation failed: %w", err)
	}

	// 4. Post HTML as a comment with a collapsible code block
	comment := formatDesignComment(assessment, htmlDesign)
	if err := a.gh.AddIssueComment(pctx.IssueNumber, comment); err != nil {
		return nil, fmt.Errorf("posting design mockup: %w", err)
	}

	return &agents.AgentResult{
		Success:     true,
		Summary:     fmt.Sprintf("Posted UI design mockup on issue #%d", pctx.IssueNumber),
		Artifacts:   []agents.Artifact{{Type: "comment", Content: comment}},
		NextContext: pctx,
	}, nil
}

func formatDesignComment(assessment, htmlDesign string) string {
	var sb strings.Builder
	sb.WriteString("## Product Design\n\n")
	sb.WriteString("### Assessment\n")
	sb.WriteString(strings.TrimSpace(assessment))
	sb.WriteString("\n\n### UI Mockup\n\n")
	sb.WriteString("<details>\n<summary>Click to view HTML mockup source</summary>\n\n")
	sb.WriteString("```html\n")
	sb.WriteString(htmlDesign)
	sb.WriteString("\n```\n\n")
	sb.WriteString("</details>\n\n")
	sb.WriteString("---\n*Generated by MicroFoundry Designer Agent*\n")
	return sb.String()
}
